version: '3.5'
services:

  db:
    # build: database/docker
    image: renatomori/softplayer_db:database
    environment:
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_USER=renatomori
      - POSTGRES_DB=bd_app
    ports:
      - 5432:5432
    networks:
      - database

  backend:
    # build: backend
    image: renatomori/softplayer_back:backend
    depends_on:
      - db
    ports:
      - 8989:8080
    networks:
      - back
      - database

  frontend:
    # build: frontend
    image: renatomori/softplayer_front:frontend
    depends_on:
      - backend
    ports:
      - 80:80
    networks:
      - front
      - back

networks:
  front:
  back:
  database: 