<?php
//backend integration

//create
function create($name,$cpf,$sexo,$birthday,$email,$nacionalidade,$naturalidade){

	$json_string = json_encode(array(
		'name'=>urlencode($name),
		'cpf'=>urlencode($cpf),
		'sexo'=>urlencode($sexo),
		'birthday'=>urlencode($birthday),
		'email'=>urlencode($email),
		'nacionalidade'=>urlencode($nacionalidade),
		'naturalidade'=>urlencode($naturalidade)
	    ));
	
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();
	
	curl_setopt($ch, CURLOPT_URL, 'http://backend:8080/app-backend/person');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_POST, 1);
	curl_setopt($ch, CURLOPT_POSTFIELDS, $json_string);
	
	$headers = array();
	$headers[] = 'Accept: */*';
	$headers[] = 'Content-Type: application/json';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	
	$result = curl_exec($ch);
	if (curl_errno($ch)) {
	    echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);
	
	// echo "<pre>$result</pre>";
	return $result;
}

//readAll
function readAll(){

	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();
	
	curl_setopt($ch, CURLOPT_URL, 'http://backend:8080/app-backend/person');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
	
	
	$headers = array();
	$headers[] = 'Accept: */*';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	
	$result = curl_exec($ch);
	if (curl_errno($ch)) {
	    echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);

	// echo "<pre>$result</pre>";
	return $result;
}

//readById
function readById($id){

	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();
	
	curl_setopt($ch, CURLOPT_URL, "http://backend:8080/app-backend/person/id/$id");
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
	
	
	$headers = array();
	$headers[] = 'Accept: */*';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	
	$result = curl_exec($ch);
	if (curl_errno($ch)) {
	    echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);

	return $result;
}

//update
function update($id,$name,$cpf,$sexo,$birthday,$email,$nacionalidade,$naturalidade){

	// echo 
	$json_string = json_encode(array(
		'name'=>urlencode($name),
		'cpf'=>urlencode($cpf),
		'sexo'=>urlencode($sexo),
		'birthday'=>urlencode($birthday),
		'email'=>urlencode($email),
		'nacionalidade'=>urlencode($nacionalidade),
		'naturalidade'=>urlencode($naturalidade)
	    ));

	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();
	
	curl_setopt($ch, CURLOPT_URL, "http://backend:8080/app-backend/person/id/$id");
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');
	
	curl_setopt($ch, CURLOPT_POSTFIELDS, $json_string);
	
	$headers = array();
	$headers[] = 'Accept: */*';
	$headers[] = 'Content-Type: application/json';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	
	$result = curl_exec($ch);
	if (curl_errno($ch)) {
	    echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);

	return $result;
}

//delete
function delete($id){
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();
	
	curl_setopt($ch, CURLOPT_URL, "http://backend:8080/app-backend/person/id/$id");
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'DELETE');
	
	
	$headers = array();
	$headers[] = 'Accept: */*';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	
	$result = curl_exec($ch);
	if (curl_errno($ch)) {
	    echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);

	return $result;
}
